name: flutter_testing_app
description: App para probar los diferentes tipos de testing en flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animate_do: ^3.3.4
  auto_route: ^9.2.2
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  fpdart: ^1.1.1
  intl: ^0.19.0
  logger: ^2.5.0
  lottie: ^3.2.0
  testing_repository:
    path: packages/testing_repository
  testing_service:
    path: packages/testing_service

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lotties/
