name: testing_service
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.7.0
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0
